spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiaotian2010/tensquare-config.git
server:
  port: 12000
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh